networks:
  mynet:
    driver: bridge

services:
  everything-ai:
    image: astrabert/everything-ai
    volumes:
      - $VOLUME
    networks:
      - mynet
    ports:
      - "7860:7860"
      - "8760:8760"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - "./qdrant_storage:/qdrant/storage"
    networks:
      - mynet
  llama_server:
    image: ghcr.io/ggerganov/llama.cpp:server
    ports:
      - "8000:8000"
    volumes:
      - "$MODELS_PATH:/models"
    networks:
      - mynet
    command: "-m /models/$MODEL --port 8000 --host 0.0.0.0 -n $MAX_TOKENS"
  
