networks:
  mynet:
    driver: bridge

services:
  everything-ai:
    image: astrabert/everything-ai
    volumes:
      - ${VOLUME}
    networks:
      - mynet
    ports:
      - "7860:7860"
      - "8760:8760"
  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - "./qdrant_storage:/qdrant/storage"
    networks:
      - mynet