docker buildx build \
--label org.opencontainers.image.title=everything-rag \
--label org.opencontainers.image.description='Introducing everything-rag, your fully customizable and local chatbot assistant!' \
--label org.opencontainers.image.url=https://github.com/AstraBert/everything-rag \
--label org.opencontainers.image.source=https://github.com/AstraBert/everything-rag --label org.opencontainers.image.version=0.1.7 \
--label org.opencontainers.image.created=2024-04-07T12:39:11.393Z \
--label org.opencontainers.image.licenses=Apache-2.0 \
--platform linux/amd64 \
--tag ghcr.io/astrabert/everything-rag:latest \
--tag ghcr.io/astrabert/everything-rag:0.1.1 \
--push .